### ISSUE TITLE
error 0xc000007b keeps appearing

### ISSUE THREAD

**Issue by ghost** [resistiv/VibRipper#1] opened 2022-08-10 00:40 UTC

**Comment by TheV360** [comment] 2022-08-14 20:56
I'm on a 64-bit operating system, and it works for me. From a quick google, I think that error message comes from trying to run a 64-bit executable (which is indeed the one supplied on the releases page) on a 32-bit operating system.

But anyway, I built the application using the x86 configuration and it worked! At least on my end. See if this works:
(oh there's official builds now)

**Comment by resistiv** [comment] 2022-08-14 21:00
Hi, could you please provide a method to reproduce this error, including OS? Could've been something wrong in my build settings...

**Comment by resistiv** [comment] 2022-08-14 21:21
I went ahead and updated the v1.0 release page to include official separate releases for x86 & x64 Windows systems.
@Jokkkkkkkkkkkkk please test the x86 build and confirm if it's working.

**Comment by ghost** [comment] 2022-08-15 21:45
@resistiv I managed to run the program but I had to install visual studio and source code and a component and i am also using x64

**Comment by resistiv** [comment] 2022-08-15 21:47
@Jokkkkkkkkkkkkk What was the component/issue in particular that required you to recompile? If I can, I'd love to implement it

**Comment by ghost** [comment] 2022-08-15 23:52
@resistiv i think is "C++ Build Tools Features"
![Captura de tela 2022-08-15 171734](https://user-images.githubusercontent.com/86070645/184754962-4da74b53-96c8-492c-bc4a-d980373eb1aa.png)
"

i just installed dont recompile when i opened the github build it worked

**Comment by resistiv** [comment] 2022-08-15 23:56
Seems that I already have this enabled, so I'm not entirely sure what the difference is here. As such, I'm gonna go ahead and close this issue. If you have any more problems in the future, please feel free to open another issue!
Also, when opening issues, please make sure to provide steps to recreate the problem, including your operating system and architecture. Thanks!

**Closed as completed by resistiv** 2022-08-15 23:56 UTC
